name: pwn-kernel-magica

services:
  pwn-kernel-magica:
    build:
        context: .
    ports:
      - '13370:13370'
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 1000M  
